version: '3.7'

services:
  app:
    image: node:12.16.1-stretch
    container_name: '${PROJECT_NAME}-api'
    env_file: .env
    command: 'yarn start:dev'
    working_dir: /app
    volumes:
      - $PWD:/app
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - internal-net
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: '${PROJECT_NAME}-db'
    volumes:
      - $PWD/docker/volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: '${PROJECT_NAME}_development'
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
