name: Template workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_test
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1

      - name: Tests
        env:
          NODE_ENV: 'test'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_DB: 'postgres_test'
          TYPEORM_DATABASE: 'postgres'
          TYPEORM_HOST: 'postgres'
          TYPEORM_PORT: '5432'
          TYPEORM_USERNAME: 'postgres'
          TYPEORM_PASSWORD: 'postgres'
        run: |
          yarn
          yarn run:migrations:test
          yarn test

  lint:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: |
          yarn
          yarn formalint

  audit:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    steps:
      - uses: actions/checkout@v1
      - name: Audit
        run: |
          yarn
          yarn audit
