name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1-stretch
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn
      - run: yarn test
        env:
          TYPEORM_HOST: postgres
          TYPEORM_PORT: 5432
          TYPEORM_USERNAME: postgres
          TYPEORM_PASSWORD: postgres
          TYPEORM_DATABASE: postgres
